build time -- 06:12:54
+ export ESMF_NETCDF=nc-config
+ ESMF_NETCDF=nc-config
+ tar xvfz /home/role.esmfmaint/pytest-input.tar.gz
tar (child): /home/role.esmfmaint/pytest-input.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
+ export ESMF_DIR=/scratch1/NCEPDEV/stmp2/role.esmfmaint/intel_18.0.4_intelmpi_g_jedwards_pio_update2
+ ESMF_DIR=/scratch1/NCEPDEV/stmp2/role.esmfmaint/intel_18.0.4_intelmpi_g_jedwards_pio_update2
+ export ESMF_COMPILER=intel
+ ESMF_COMPILER=intel
+ export ESMF_COMM=intelmpi
+ ESMF_COMM=intelmpi
+ export ESMF_BOPT=g
+ ESMF_BOPT=g
+ export ESMF_TESTEXHAUSTIVE=ON
+ ESMF_TESTEXHAUSTIVE=ON
+ export ESMF_TESTWITHTHREADS=ON
+ ESMF_TESTWITHTHREADS=ON
+ python3 setup.py test_examples_dryrun
running test_examples_dryrun
error: [Errno 2] No such file or directory: ''
+ python3 setup.py test_regrid_from_file_dryrun
running test_regrid_from_file_dryrun
Traceback (most recent call last):
  File "src/ESMF/test/regrid_from_file/run_regrid_from_file_dryrun.py", line 14, in <module>
    from ESMF.test.regrid_from_file.regrid_from_file_consts import DATA_SUBDIR, DATA_URL_ROOT
  File "/scratch1/NCEPDEV/stmp2/role.esmfmaint/intel_18.0.4_intelmpi_g_jedwards_pio_update2/src/addon/ESMPy/src/ESMF/__init__.py", line 69, in <module>
    from ESMF.api.esmpymanager import *
  File "/scratch1/NCEPDEV/stmp2/role.esmfmaint/intel_18.0.4_intelmpi_g_jedwards_pio_update2/src/addon/ESMPy/src/ESMF/api/esmpymanager.py", line 11, in <module>
    from ESMF.interface.cbindings import *
  File "/scratch1/NCEPDEV/stmp2/role.esmfmaint/intel_18.0.4_intelmpi_g_jedwards_pio_update2/src/addon/ESMPy/src/ESMF/interface/cbindings.py", line 13, in <module>
    from ESMF.interface.loadESMF import _ESMF
  File "/scratch1/NCEPDEV/stmp2/role.esmfmaint/intel_18.0.4_intelmpi_g_jedwards_pio_update2/src/addon/ESMPy/src/ESMF/interface/loadESMF.py", line 36, in <module>
    with open(esmfmk, 'r') as MKFILE:
FileNotFoundError: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "setup.py", line 273, in <module>
    'test_regrid_from_file_parallel': TestRegridFromFileParallelCommand})
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 192, in run
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'src/ESMF/test/regrid_from_file/run_regrid_from_file_dryrun.py']' returned non-zero exit status 1.
