build time -- 2022-05-13 01:27:32
running test_examples
test_field_read (examples.exampletest.TestExamples) ... Abort with message unexpected record in file /lfs/h1/emc/ptmp/Mark.Potts/intel_19.1.3_mpi_g_develop/src/Infrastructure/IO/PIO/ParallelIO/src/clib/pio_darray_int.c at line 1458
Obtained 10 stack frames.
/lfs/h1/emc/ptmp/Mark.Potts/intel_19.1.3_mpi_g_develop/DEFAULTINSTALLDIR/lib/libg/Unicos.intel.64.mpi.default/libesmf_fullylinked.so(print_trace+0x29) [0x1478f95afcb9]
/lfs/h1/emc/ptmp/Mark.Potts/intel_19.1.3_mpi_g_develop/DEFAULTINSTALLDIR/lib/libg/Unicos.intel.64.mpi.default/libesmf_fullylinked.so(piodie+0x40) [0x1478f95ada80]
/lfs/h1/emc/ptmp/Mark.Potts/intel_19.1.3_mpi_g_develop/DEFAULTINSTALLDIR/lib/libg/Unicos.intel.64.mpi.default/libesmf_fullylinked.so(pio_read_darray_nc_serial+0x14c) [0x1478f95d9f9c]
/lfs/h1/emc/ptmp/Mark.Potts/intel_19.1.3_mpi_g_develop/DEFAULTINSTALLDIR/lib/libg/Unicos.intel.64.mpi.default/libesmf_fullylinked.so(PIOc_read_darray+0x284) [0x1478f95d7aa4]
/lfs/h1/emc/ptmp/Mark.Potts/intel_19.1.3_mpi_g_develop/DEFAULTINSTALLDIR/lib/libg/Unicos.intel.64.mpi.default/libesmf_fullylinked.so(_ZN5ESMCI11PIO_Handler9arrayReadEPNS_5ArrayEPKcPiS5_+0x77d) [0x1478f7495c2d]
/lfs/h1/emc/ptmp/Mark.Potts/intel_19.1.3_mpi_g_develop/DEFAULTINSTALLDIR/lib/libg/Unicos.intel.64.mpi.default/libesmf_fullylinked.so(_ZN5ESMCI2IO4readEPi+0x27e) [0x1478f7038fde]
/lfs/h1/emc/ptmp/Mark.Potts/intel_19.1.3_mpi_g_develop/DEFAULTINSTALLDIR/lib/libg/Unicos.intel.64.mpi.default/libesmf_fullylinked.so(_ZN5ESMCI2IO4readERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE15ESMC_IOFmt_FlagPi+0x9f) [0x1478f703855f]
/lfs/h1/emc/ptmp/Mark.Potts/intel_19.1.3_mpi_g_develop/DEFAULTINSTALLDIR/lib/libg/Unicos.intel.64.mpi.default/libesmf_fullylinked.so(c_esmc_ioread_+0x1cc) [0x1478f702841c]
/lfs/h1/emc/ptmp/Mark.Potts/intel_19.1.3_mpi_g_develop/DEFAULTINSTALLDIR/lib/libg/Unicos.intel.64.mpi.default/libesmf_fullylinked.so(esmf_iomod_mp_esmf_ioread_+0x39f) [0x1478f863577d]
/lfs/h1/emc/ptmp/Mark.Potts/intel_19.1.3_mpi_g_develop/DEFAULTINSTALLDIR/lib/libg/Unicos.intel.64.mpi.default/libesmf_fullylinked.so(esmf_fieldprmod_mp_esmf_fieldread_+0xc11) [0x1478f81ef810]
MPICH Notice [Rank 0] [job id ] [Fri May 13 01:47:45 2022] [nid001002] - Abort(-1) (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0

Traceback (most recent call last):
  File "setup.py", line 278, in <module>
    'test_regrid_from_file_parallel': TestRegridFromFileParallelCommand})
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 15, in wrapper
    return func(self)
  File "setup.py", line 171, in run
    AbstractESMFNoseCommand.run(self)
  File "setup.py", line 49, in run
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nosetests', '-vs', '--with-xunit', '-a', '!slow,!parallel', 'examples/exampletest.py']' returned non-zero exit status 255.
